service: serverless-webpack-babel-boilerplate

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev

functions:
  houses:
    handler: src/handlers/houses.handler
    events:
      - http:
          method: get
          path: houses
          integration: lambda
  heir:
    handler: src/handlers/heir.handler
    events:
      - http:
          method: get
          path: heir
          integration: lambda

plugins:
  - serverless-webpack

package:
  individually: true
